name: Check Icon Sync with Python

on:
  push:
    paths:
      - 'icons/dark/**'
      - 'icons/light/**'
  pull_request:
    paths:
      - 'icons/dark/**'
      - 'icons/light/**'

jobs:
  icon-sync-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  

      - name: Run icon sync checker
        run: python scripts/check_icon_sync.py
